sudo: required
services:
  - docker

env:
    global:
        - SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_d72dae917a6c_key -iv $encrypted_d72dae917a6c_iv -in kubernetes-1-249219-53a206d698da.json.enc -out kubernetes-1-249219-53a206d698da.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project kubernetes-1-249219
  - gcloud config set compute/zone us-central1-b
  - gcloud container clusters get-credentials k8s-1
  ## - gcloud container clusters get-credentials k8s-1 --zone us-central1-a --project kubernetes-1-249219
  - docker login -u "$DOCKER_ID" --password  $DOCKER_PASSWORD
  - docker build -t singh0009/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true singh0009/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
    

 