apiVersion: skaffold/v1beta13	# 	version of the configuration.
kind: Config	# 	always Config.
build: 	# 	describes how images are built.
  local:
    push: false
  artifacts:
    - image: singh0009/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*.js": .
        "**/*.css": .
        "**/*.html": .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml